// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICanvasSystem {
  function paint(uint32 x, uint32 y, uint32 color) external returns (uint32);
}
